out_dir: exp
log_dir: tensorboard/exp/acoustic

use_amp: true

max_train_steps: -1
nepochs: 80
checkpoint_epoch_interval: 22

feats_criterion: mae

pitch_reg_weight: 0.3
pitch_reg_decay_size: 900

force_fix_vuv: true

stream_wise_loss: false
use_detect_anomaly: false

optim:
  optimizer:
    name: RAdam
    params:
      lr: 0.001
      betas: [0.9, 0.999]
      weight_decay: 0.0
  lr_scheduler:
    name: StepLR
    params:
      step_size: 20
      gamma: 0.5

resume:
  checkpoint:
  load_optimizer: false

cudnn:
  benchmark: false
  deterministic: true
