nnsvs_root:                 nnsvs
spk:                        unnamed
tag:                        upt3_prototyping_notebook

out_dir:                    data

exclude_songs:              []

table_path:                 dic/upt3_jp.table
question_path:              hed/upt3_jp.hed

sample_rate:                44100

# stage 0
stage0:
    db_root:                ../singing_database

    segmentation_mode:      middle
    middle_frequency:       2

    # Choices are [strict, middle, lenient]
    vowel_duration_check:   middle

# stage 1
timelag_features:           defaults
duration_features:          defaults
acoustic_features:          static_deltadelta

trajectory_smoothing: false
trajectory_smoothing_cutoff: 50
trajectory_smoothing_cutoff_f0: 20

# stage 4
# symlink during training in notebook.
acoustic_model:             acoustic_current
acoustic_train:             myconfig
acoustic_data:              myconfig

duration_model:             duration_mdnv2
duration_train:             myconfig
duration_data:              myconfig

timelag_model:              timelag_mdnv2
timelag_train:              myconfig
timelag_data:               myconfig

pretrained_expdir:

# stage 6
timelag_synthesis:          defaults
duration_synthesis:         defaults
acoustic_synthesis:         defaults

# latest.pth or best.pth are recommended
timelag_eval_checkpoint:    best_loss.pth
duration_eval_checkpoint:   best_loss.pth
acoustic_eval_checkpoint:   best_loss.pth

# postfilter stuff
postfilter_model:           postfilter
postfilter_train:           myconfig
postfilter_data:            myconfig

# vocoder stuff (stage 8)
vocoder_model:
pretrained_vocoder_checkpoint:
vocoder_eval_checkpoint:
