# Copyright (c) 2020 Ryuichi Yamamoto
# Copyright (c) 2020 oatsu

trained_for_enunu:      false

question_path:          hed/intunist_jp.hed
table_path:             dic/intunist_jp.table

defaults:
    - hydra/job_logging: colorlog
    - hydra/hydra_logging: colorlog

verbose:                100

sample_rate:            44100
gain_normalize:         true

frame_period:           5
log_f0_conditioning:    true
vibrato_scale: 1.0

# Use ground truth duration or not
# if true, time-lag and duration models will not be used.
ground_truth_duration:  false

# If not empty, try to search statisics in the directory
stats_dir:              dump/Unnamed/norm
# If not empty, try to search models in the directory
model_dir:              exp/Unnamed

acoustic:
    question_path:      hed/intunist_jp.hed
    checkpoint:         best_loss.pth
    in_scaler_path:     null
    out_scaler_path:    null
    # model_yaml:
    subphone_features:  coarse_coding
    relative_f0:        true
#    post_filter:        true
    # 'post_ftiler' is legacy option for ENUNU prior to 5.1.
    post_filter_type:   merlin

duration:
    question_path:      hed/intunist_jp.hed
    checkpoint:         best_loss.pth
    in_scaler_path:     null
    out_scaler_path:    null

timelag:
    question_path:      hed/intunist_jp.hed
    checkpoint:         best_loss.pth
    in_scaler_path:     null
    out_scaler_path:    null
    allowed_range:      [-150, 150]
    allowed_range_rest: [-150, 250]

postfilter:
    question_path:      hed/intunist_jp.hed
    checkpoint:         latest.pth
    in_scaler_path:     null
    out_scaler_path:    null

