# (mgc, lf0, vuv, bap)
stream_sizes: [180, 3, 1, 15]
has_dynamic_features: [true, true, false, true]
num_windows: 3
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.acoustic_models.ResF0VariancePredictor
  in_dim: 372
  out_dim: 199
  hidden_dim: 512
  num_layers: 5
  kernel_size: 5
  dropout: 0.4
  init_type: "none"
  use_mdn: false
  num_gaussians: 8
  dim_wise: false

  in_lf0_idx: 389
  out_lf0_idx: 180
  in_lf0_min: null
  in_lf0_max: null
  out_lf0_mean: null
  out_lf0_scale: null
