# (mgc, lf0, vuv, bap)
stream_sizes: [180, 3, 1, 15]
has_dynamic_features: [true, true, false, true]
num_windows: 3
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.acoustic_models.ResSkipF0FFConvLSTM
  in_dim: 372
  out_dim: 199
  ff_hidden_dim: 2048
  conv_hidden_dim: 1024
  lstm_hidden_dim: 256
  num_lstm_layers: 2
  bidirectional: true
  skip_inputs: false
  dropout: 0.1
  init_type: "none"
  use_mdn: false
  num_gaussians: 8
  dim_wise: true

  in_lf0_idx: 389
  out_lf0_idx: 180
  in_lf0_min: null
  in_lf0_max: null
  out_lf0_mean: null
  out_lf0_scale: null
