# (mgc, lf0, vuv, bap)
stream_sizes: [180, 3, 1, 5]
has_dynamic_features: [true, true, false, false]
num_windows: 3
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.model.FFConvLSTM
  in_dim: 364
  out_dim: 189
  ff_hidden_dim: 2048
  conv_hidden_dim: 1024
  lstm_hidden_dim: 256
  num_lstm_layers: 2
  bidirectional: true
  dropout: 0.1
  init_type: "none"
