#for dev5e
# (mgc, lf0, vuv, bap)
stream_sizes: [60, 1, 1, 5]
has_dynamic_features: [false, false, false, false]
num_windows: 1
stream_weights:

netG:
  _target_: nnsvs.acoustic_models.NPSSMultistreamParametricModel
  in_dim: 357
  out_dim: 67

  stream_sizes: [60, 1, 1, 5]
  reduction_factor: 4

  # NOTE: you MUST set in_lf0_idx and out_lf0_idx correctly
  # otherwise the model does't work at all
  in_rest_idx: 0
  in_lf0_idx: 310
  out_lf0_idx: 60
  # Please leave the following parameters unspecified if you want to
  # find the corresponding values automatically from in/out scalers.
  in_lf0_min: null
  in_lf0_max: null
  out_lf0_mean: null
  out_lf0_scale: null

  vuv_model_bap0_conditioning: true
  npss_style_conditioning: false

  # A separate model for modeling continuous log-F0
  lf0_model:
    _target_: nnsvs.model.ResSkipF0FFConvLSTM
    in_dim: 357
    out_dim: 1
    ff_hidden_dim: 256
    conv_hidden_dim: 128
    lstm_hidden_dim: 64
    dropout: 0.1
    num_lstm_layers: 2
    bidirectional: true
    init_type: "none"
    use_mdn: false
    num_gaussians: 8
    dim_wise: true
    in_lf0_idx: 310
    out_lf0_idx: 0
    in_lf0_min: null
    in_lf0_max: null
    out_lf0_mean: null
    out_lf0_scale: null

  # Spectral parameter prediction model
  mgc_model:
    _target_: nnsvs.acoustic_models.BiLSTMNonAttentiveDecoder
    in_dim: 358 # (x, lf0)
    out_dim: 60
    in_ph_start_idx: 50
    in_ph_end_idx: 98
    embed_dim: 256
    ff_hidden_dim: 1024
    conv_hidden_dim: 512
    lstm_hidden_dim: 256
    num_lstm_layers: 3
    decoder_layers: 2
    decoder_hidden_dim: 1024
    prenet_layers: 0
    prenet_hidden_dim: 192
    prenet_dropout: 0.5
    zoneout: 0.0
    reduction_factor: 2
    downsample_by_conv: true
    postnet_layers: 5
    postnet_channels: 512
    postnet_kernel_size: 5
    postnet_dropout: 0.0
    init_type: "none"

  # Aperiodic parameter prediction model
  bap_model:
    _target_: nnsvs.acoustic_models.BiLSTMNonAttentiveDecoder
    in_dim: 358 # (x, lf0)
    out_dim: 5
    in_ph_start_idx: 50
    in_ph_end_idx: 98
    embed_dim: 256
    ff_hidden_dim: 1024
    conv_hidden_dim: 512
    lstm_hidden_dim: 256
    num_lstm_layers: 3
    decoder_layers: 2
    decoder_hidden_dim: 256
    prenet_layers: 0
    prenet_hidden_dim: 192
    prenet_dropout: 0.5
    zoneout: 0.0
    reduction_factor: 2
    downsample_by_conv: true
    postnet_layers: 5
    postnet_channels: 512
    postnet_kernel_size: 5
    postnet_dropout: 0.0
    init_type: "none"

  # V/UV prediction model
  vuv_model:
    _target_: nnsvs.model.FFConvLSTM
    in_dim: 359 # (x, lf0, bap0)
    in_ph_start_idx: 50
    in_ph_end_idx: 98
    embed_dim: 256
    ff_hidden_dim: 256
    conv_hidden_dim: 128
    lstm_hidden_dim: 64
    num_lstm_layers: 2
    bidirectional: true
    out_dim: 1
    dropout: 0.1
    init_type: "none"
