# (mgc, lf0, vuv, bap)
stream_sizes: [180, 3, 1, 5]
has_dynamic_features: [true, true, false, false]
num_windows: 3
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.model.VariancePredictor
  in_dim: 364
  out_dim: 189
  hidden_dim: 512
  num_layers: 5
  kernel_size: 5
  dropout: 0.5
  init_type: "none"
  use_mdn: false
  num_gaussians: 8
  dim_wise: false
