# (mgc, lf0, vuv, bap)
stream_sizes: [180, 3, 1, 15]
has_dynamic_features: [true, true, false, true]
num_windows: 3
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.acoustic_models.ResF0NonAttentiveTacotron
  in_dim: 372
  out_dim: 199
  # encoder
  encoder_lstm_hidden_dim: 512
  encoder_num_lstm_layers: 3
  encoder_dropout: 0.0
  # decoder
  decoder_layers: 2
  decoder_hidden_dim: 1024
  decoder_prenet_layers: 2
  decoder_prenet_hidden_dim: 1024
  decoder_prenet_dropout: 0.5
  decoder_zoneout: 0.1
  # postnet
  postnet_layers: 5
  postnet_channels: 512
  postnet_kernel_size: 5
  postnet_dropout: 0.0
  # other
  reduction_factor: 2
  init_type: "none"
  # resf0 config
  in_lf0_idx: 389
  out_lf0_idx: 180
  in_lf0_min: null
  in_lf0_max: null
  out_lf0_mean: null
  out_lf0_scale: null
